import { promises as fs } from 'node:fs';
import path from 'node:path';
import { ALLOWLIST_PATTERNS, SCAN_RULES } from './scan-rules.js';

/**
 * The pre-commit hook is generated as a standalone, dependency-free Node
 * script committed inside .baton/hooks/. Every relay member gets secret
 * scanning on .baton/ changes even if they never installed the baton CLI.
 * The .git/hooks/pre-commit shim (not committed — git ignores it) just
 * executes it.
 */
export function generateHookScript(): string {
  return `#!/usr/bin/env node
// Generated by "baton init" — scans staged .baton/ changes for secrets.
// Regenerate with "baton init --refresh-hook". Do not hand-edit.
import { execFileSync } from 'node:child_process';

const RULES = ${JSON.stringify(SCAN_RULES, null, 2)};

const ALLOWLIST = ${JSON.stringify(ALLOWLIST_PATTERNS, null, 2)};

function compile(source) {
  return source.startsWith('(?i)')
    ? new RegExp(source.slice(4), 'gi')
    : new RegExp(source, 'g');
}

const rules = RULES.map((r) => ({ ...r, regex: compile(r.pattern) }));
const allow = ALLOWLIST.map(compile);

function git(...args) {
  return execFileSync('git', args, { encoding: 'utf8' });
}

const staged = git('diff', '--cached', '--name-only', '--diff-filter=ACM', '--', '.baton')
  .split('\\n')
  .filter(Boolean);

const findings = [];
for (const file of staged) {
  let content;
  try {
    content = git('show', ':' + file);
  } catch {
    continue;
  }
  content.split(/\\r?\\n/).forEach((line, idx) => {
    if (allow.some((a) => (a.lastIndex = 0, a.test(line)))) return;
    for (const rule of rules) {
      rule.regex.lastIndex = 0;
      const m = rule.regex.exec(line);
      if (m) {
        const v = m[0];
        const preview = v.length <= 8 ? '********' : v.slice(0, 4) + '…' + v.slice(-2);
        findings.push(file + ':' + (idx + 1) + '  [' + rule.id + '] ' + preview);
      }
    }
  });
}

if (findings.length > 0) {
  console.error('baton pre-commit: potential secret(s) in .baton/ — commit blocked');
  for (const f of findings) console.error('  ' + f);
  console.error('Reference secrets by NAME only, never value.');
  console.error('False positive? Append "baton-allow-secret" to the line.');
  process.exit(1);
}
`;
}

const SHIM = `#!/bin/sh
# Installed by "baton init" — runs the committed Baton secret scan.
if command -v node >/dev/null 2>&1; then
  node "$(git rev-parse --show-toplevel)/.baton/hooks/pre-commit.mjs" || exit 1
else
  echo "baton pre-commit: node not found on PATH; skipping secret scan" >&2
fi
`;

export interface HookInstallResult {
  scriptPath: string;
  shimPath: string;
  shimInstalled: boolean;
}

export async function installHook(repoRoot: string): Promise<HookInstallResult> {
  const hooksDir = path.join(repoRoot, '.baton', 'hooks');
  const scriptPath = path.join(hooksDir, 'pre-commit.mjs');
  await fs.mkdir(hooksDir, { recursive: true });
  await fs.writeFile(scriptPath, generateHookScript(), 'utf8');

  const gitHooksDir = path.join(repoRoot, '.git', 'hooks');
  const shimPath = path.join(gitHooksDir, 'pre-commit');
  let shimInstalled = false;
  try {
    await fs.mkdir(gitHooksDir, { recursive: true });
    let existing: string | null = null;
    try {
      existing = await fs.readFile(shimPath, 'utf8');
    } catch {
      // no existing hook
    }
    if (existing === null || existing.includes('baton')) {
      await fs.writeFile(shimPath, SHIM, { encoding: 'utf8', mode: 0o755 });
      shimInstalled = true;
    }
    // An existing non-baton hook is left untouched; caller warns the user.
  } catch {
    // .git/hooks unwritable (worktrees, odd setups) — scan still runs at pass time
  }
  return { scriptPath, shimPath, shimInstalled };
}
